# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\graficador.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets, QtChart
from ip_graf import obtener_tabla_ip
from tiempo_graf import obtener_grafico_dia, obtener_grafico_hora
from metodo_graf import obtener_grafico_metodo

class Ui_Graficador(object):
    def setupUi(self, Graficador):
        Graficador.setObjectName("Graficador")
        Graficador.resize(319, 265)
        self.line_path_file = QtWidgets.QLineEdit(Graficador)
        self.line_path_file.setGeometry(QtCore.QRect(50, 50, 113, 20))
        self.line_path_file.setObjectName("line_path_file")
        self.bot_select_file = QtWidgets.QPushButton(Graficador)
        self.bot_select_file.setGeometry(QtCore.QRect(180, 50, 71, 21))
        self.bot_select_file.setObjectName("bot_select_file")
        self.bot_ip = QtWidgets.QPushButton(Graficador)
        self.bot_ip.setEnabled(False)
        self.bot_ip.setGeometry(QtCore.QRect(20, 150, 75, 23))
        self.bot_ip.setObjectName("bot_ip")
        self.bot_tiempo = QtWidgets.QPushButton(Graficador)
        self.bot_tiempo.setEnabled(False)
        self.bot_tiempo.setGeometry(QtCore.QRect(120, 150, 75, 23))
        self.bot_tiempo.setObjectName("bot_tiempo")
        self.bot_metodo = QtWidgets.QPushButton(Graficador)
        self.bot_metodo.setEnabled(False)
        self.bot_metodo.setGeometry(QtCore.QRect(220, 150, 75, 23))
        self.bot_metodo.setAutoDefault(True)
        self.bot_metodo.setObjectName("bot_prot")
        self.bot_dir = QtWidgets.QPushButton(Graficador)
        self.bot_dir.setEnabled(False)
        self.bot_dir.setGeometry(QtCore.QRect(70, 200, 75, 23))
        self.bot_dir.setObjectName("bot_metodo")
        self.bot_navegador = QtWidgets.QPushButton(Graficador)
        self.bot_navegador.setEnabled(False)
        self.bot_navegador.setGeometry(QtCore.QRect(180, 200, 75, 23))
        self.bot_navegador.setObjectName("bot_navegador")

        self._retranslateUi(Graficador)
        self.bot_select_file.clicked.connect(self._file_selection)
        self.line_path_file.textChanged.connect(lambda:self.bot_ip.setEnabled(bool(self.line_path_file.text())))
        self.line_path_file.textChanged.connect(lambda:self.bot_tiempo.setEnabled(bool(self.line_path_file.text())))
        self.line_path_file.textChanged.connect(lambda:self.bot_metodo.setEnabled(bool(self.line_path_file.text())))

        self.bot_ip.clicked.connect(self._graficar_ip)
        self.bot_tiempo.clicked.connect(self._graficar_tiempo)
        self.bot_metodo.clicked.connect(self._graficar_metodo)

        QtCore.QMetaObject.connectSlotsByName(Graficador)
        Graficador.setTabOrder(self.line_path_file, self.bot_select_file)

    def _retranslateUi(self, Graficador):
        _translate = QtCore.QCoreApplication.translate
        Graficador.setWindowTitle(_translate("Graficador", "Graficador"))
        self.bot_select_file.setText(_translate("Graficador", "Seleccionar"))
        self.bot_ip.setText(_translate("Graficador", "IP"))
        self.bot_tiempo.setText(_translate("Graficador", "Tiempo"))
        self.bot_metodo.setText(_translate("Graficador", "Método"))
        self.bot_dir.setText(_translate("Graficador", "Directorio"))
        self.bot_navegador.setText(_translate("Graficador", "Navegador"))

    def _file_selection(self):
        file_path = (QtWidgets.QFileDialog.getOpenFileName(None, 'Open'))
        self.line_path_file.setText(file_path[0])
    
    def _graficar_tiempo(self):
        self.grafico_horas = obtener_grafico_hora(self.line_path_file.text())
        self.grafico_dias = obtener_grafico_dia(self.line_path_file.text())
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.addWidget(self.grafico_horas)
        self.layout.addWidget(self.grafico_dias)
        self.graficos = QtWidgets.QWidget()
        self.graficos.setLayout(self.layout)
        self.graficos.show()

    def _graficar_ip(self):
        self.tabla_ip = obtener_tabla_ip(self.line_path_file.text())
        self.tabla_ip.show()

    def _graficar_metodo(self):
        self.view = QtChart.QChartView(obtener_grafico_metodo(self.line_path_file.text()))
        self.view.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Graficador = QtWidgets.QDialog()
    ui = Ui_Graficador()
    ui.setupUi(Graficador)
    Graficador.show()
    sys.exit(app.exec_())
