# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\parseador.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from log_to_csv import log_to_csv

class Ui_Parseador(object):
    def setupUi(self, Parseador):
        Parseador.setObjectName("Parseador")
        Parseador.resize(319, 265)
        self.path_file = QtWidgets.QLineEdit(Parseador)
        self.path_file.setGeometry(QtCore.QRect(50, 70, 113, 20))
        self.path_file.setObjectName("path_file")
        self.select_file = QtWidgets.QPushButton(Parseador)
        self.select_file.setGeometry(QtCore.QRect(180, 70, 71, 21))
        self.select_file.setObjectName("select_file")
        self.combox_format = QtWidgets.QComboBox(Parseador)
        self.combox_format.setEnabled(False)
        self.combox_format.setGeometry(QtCore.QRect(50, 170, 69, 22))
        self.combox_format.setObjectName("combox_format")
        self.combox_format.addItem("")
        self.label_formato = QtWidgets.QLabel(Parseador)
        self.label_formato.setGeometry(QtCore.QRect(60, 150, 47, 13))
        self.label_formato.setObjectName("label_formato")
        self.bot_parsear = QtWidgets.QPushButton(Parseador)
        self.bot_parsear.setEnabled(False)
        self.bot_parsear.setGeometry(QtCore.QRect(160, 170, 75, 23))
        self.bot_parsear.setObjectName("bot_parsear")
        self.label_formato.setBuddy(self.combox_format)

        self._retranslateUi(Parseador)
        self.select_file.clicked.connect(self._file_selection) # type: ignore
        
        self.path_file.textChanged.connect(lambda:self.combox_format.setEnabled(bool(self.path_file.text()))) # type: ignore
        self.path_file.textChanged.connect(lambda:self.bot_parsear.setEnabled(bool(self.path_file.text()))) # type: ignore
        self.path_file.textChanged.connect(lambda:self.label_formato.setEnabled(bool(self.path_file.text()))) # type: ignore
        
        self.bot_parsear.clicked.connect(self._parsear)

        QtCore.QMetaObject.connectSlotsByName(Parseador)

    def _file_selection(self):
        file_path = (QtWidgets.QFileDialog.getOpenFileName(None, 'Open'))
        self.path_file.setText(file_path[0])

    def _parsear(self):
        path = self.path_file.text()
        try:
            open(path)
        except:
            print("Error al abrir el archivo")
        else:
            log_to_csv(path)

    def _retranslateUi(self, Parseador):
        _translate = QtCore.QCoreApplication.translate
        Parseador.setWindowTitle(_translate("Parseador", "Parseador"))
        self.select_file.setText(_translate("Parseador", "Seleccionar"))
        self.combox_format.setItemText(0, _translate("Parseador", "Apache"))
        self.label_formato.setText(_translate("Parseador", "Formato"))
        self.bot_parsear.setText(_translate("Parseador", "Parsear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Parseador = QtWidgets.QDialog()
    ui = Ui_Parseador()
    ui.setupUi(Parseador)
    Parseador.show()
    sys.exit(app.exec_())
