# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\conversor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Conversor(object):
    def setupUi(self, Conversor):
        Conversor.setObjectName("Conversor")
        Conversor.resize(264, 159)
        self.gridLayout = QtWidgets.QGridLayout(Conversor)
        self.gridLayout.setObjectName("gridLayout")
        self.combox_formato = QtWidgets.QComboBox(Conversor)
        self.combox_formato.setObjectName("combox_formato")
        self.combox_formato.addItem("")
        self.gridLayout.addWidget(self.combox_formato, 0, 1, 1, 1)
        self.label_formato = QtWidgets.QLabel(Conversor)
        self.label_formato.setObjectName("label_formato")
        self.gridLayout.addWidget(self.label_formato, 0, 0, 1, 1)
        self.bbox = QtWidgets.QDialogButtonBox(Conversor)
        self.bbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bbox.setObjectName("bbox")
        self.gridLayout.addWidget(self.bbox, 2, 0, 1, 2)
        self.label_archivos_seleccionados = QtWidgets.QLabel(Conversor)
        self.label_archivos_seleccionados.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_archivos_seleccionados.setObjectName("label_archivos_seleccionados")
        self.gridLayout.addWidget(self.label_archivos_seleccionados, 1, 0, 1, 1)
        self.but_seleccionar = QtWidgets.QPushButton(Conversor)
        self.but_seleccionar.setObjectName("but_seleccionar")
        self.gridLayout.addWidget(self.but_seleccionar, 1, 1, 1, 1)

        self.retranslateUi(Conversor)
        QtCore.QMetaObject.connectSlotsByName(Conversor)

    def retranslateUi(self, Conversor):
        _translate = QtCore.QCoreApplication.translate
        Conversor.setWindowTitle(_translate("Conversor", "Conversor"))
        self.combox_formato.setItemText(0, _translate("Conversor", "Ejemplo"))
        self.label_formato.setText(_translate("Conversor", "Formato de entrada"))
        self.label_archivos_seleccionados.setText(_translate("Conversor", "Archivos seleccionados:"))
        self.but_seleccionar.setText(_translate("Conversor", "Seleccionar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Conversor = QtWidgets.QDialog()
    ui = Ui_Conversor()
    ui.setupUi(Conversor)
    Conversor.show()
    sys.exit(app.exec_())
