# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\selector_de_graficos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectorGraficos(object):
    def setupUi(self, SelectorGraficos):
        SelectorGraficos.setObjectName("SelectorGraficos")
        SelectorGraficos.resize(299, 158)
        self.gridLayout = QtWidgets.QGridLayout(SelectorGraficos)
        self.gridLayout.setObjectName("gridLayout")
        self.combox_control = QtWidgets.QComboBox(SelectorGraficos)
        self.combox_control.setObjectName("combox_control")
        self.combox_control.addItem("")
        self.combox_control.setItemText(0, "")
        self.gridLayout.addWidget(self.combox_control, 0, 0, 1, 2)
        self.label_vs = QtWidgets.QLabel(SelectorGraficos)
        self.label_vs.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vs.setObjectName("label_vs")
        self.gridLayout.addWidget(self.label_vs, 0, 2, 1, 1)
        self.combox_tratamiento = QtWidgets.QComboBox(SelectorGraficos)
        self.combox_tratamiento.setEnabled(False)
        self.combox_tratamiento.setObjectName("combox_tratamiento")
        self.combox_tratamiento.addItem("")
        self.gridLayout.addWidget(self.combox_tratamiento, 0, 3, 1, 1)
        self.label_tipo = QtWidgets.QLabel(SelectorGraficos)
        self.label_tipo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tipo.setObjectName("label_tipo")
        self.gridLayout.addWidget(self.label_tipo, 1, 0, 1, 1)
        self.combox_grafico = QtWidgets.QComboBox(SelectorGraficos)
        self.combox_grafico.setEnabled(False)
        self.combox_grafico.setObjectName("combox_grafico")
        self.combox_grafico.addItem("")
        self.combox_grafico.setItemText(0, "")
        self.gridLayout.addWidget(self.combox_grafico, 1, 1, 1, 2)
        self.bbox = QtWidgets.QDialogButtonBox(SelectorGraficos)
        self.bbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bbox.setObjectName("bbox")
        self.gridLayout.addWidget(self.bbox, 2, 2, 1, 2)

        self.retranslateUi(SelectorGraficos)
        self.combox_control.currentIndexChanged['int'].connect(self.combox_tratamiento.update) # type: ignore
        self.combox_control.currentIndexChanged['int'].connect(self.combox_grafico.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectorGraficos)

    def retranslateUi(self, SelectorGraficos):
        _translate = QtCore.QCoreApplication.translate
        SelectorGraficos.setWindowTitle(_translate("SelectorGraficos", "Selector de graficos"))
        self.label_vs.setText(_translate("SelectorGraficos", "vs"))
        self.combox_tratamiento.setItemText(0, _translate("SelectorGraficos", "Todos"))
        self.label_tipo.setText(_translate("SelectorGraficos", "Tipo de\n"
" gráfico"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectorGraficos = QtWidgets.QDialog()
    ui = Ui_SelectorGraficos()
    ui.setupUi(SelectorGraficos)
    SelectorGraficos.show()
    sys.exit(app.exec_())
