# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\selector_de_filtros.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectorFiltros(object):
    def setupUi(self, SelectorFiltros):
        SelectorFiltros.setObjectName("SelectorFiltros")
        SelectorFiltros.resize(248, 176)
        self.gridLayout = QtWidgets.QGridLayout(SelectorFiltros)
        self.gridLayout.setObjectName("gridLayout")
        self.label_organismo = QtWidgets.QLabel(SelectorFiltros)
        self.label_organismo.setObjectName("label_organismo")
        self.gridLayout.addWidget(self.label_organismo, 0, 0, 1, 1)
        self.check_organismo = QtWidgets.QCheckBox(SelectorFiltros)
        self.check_organismo.setText("")
        self.check_organismo.setObjectName("check_organismo")
        self.gridLayout.addWidget(self.check_organismo, 0, 1, 1, 1)
        self.combox_organismo = QtWidgets.QComboBox(SelectorFiltros)
        self.combox_organismo.setEnabled(False)
        self.combox_organismo.setObjectName("combox_organismo")
        self.combox_organismo.addItem("")
        self.combox_organismo.addItem("")
        self.gridLayout.addWidget(self.combox_organismo, 1, 1, 1, 1)
        self.label_error = QtWidgets.QLabel(SelectorFiltros)
        self.label_error.setObjectName("label_error")
        self.gridLayout.addWidget(self.label_error, 2, 0, 1, 1)
        self.check_error = QtWidgets.QCheckBox(SelectorFiltros)
        self.check_error.setText("")
        self.check_error.setObjectName("check_error")
        self.gridLayout.addWidget(self.check_error, 2, 1, 1, 1)
        self.dsbox_error = QtWidgets.QDoubleSpinBox(SelectorFiltros)
        self.dsbox_error.setEnabled(False)
        self.dsbox_error.setMaximum(1000.0)
        self.dsbox_error.setProperty("value", 20.0)
        self.dsbox_error.setObjectName("dsbox_error")
        self.gridLayout.addWidget(self.dsbox_error, 3, 1, 1, 1)
        self.label_p = QtWidgets.QLabel(SelectorFiltros)
        self.label_p.setObjectName("label_p")
        self.gridLayout.addWidget(self.label_p, 4, 0, 1, 1)
        self.check_p = QtWidgets.QCheckBox(SelectorFiltros)
        self.check_p.setText("")
        self.check_p.setObjectName("check_p")
        self.gridLayout.addWidget(self.check_p, 4, 1, 1, 1)
        self.dsbox_p = QtWidgets.QDoubleSpinBox(SelectorFiltros)
        self.dsbox_p.setEnabled(False)
        self.dsbox_p.setDecimals(3)
        self.dsbox_p.setMaximum(1.0)
        self.dsbox_p.setSingleStep(0.1)
        self.dsbox_p.setObjectName("dsbox_p")
        self.gridLayout.addWidget(self.dsbox_p, 5, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(SelectorFiltros)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 0, 1, 2)

        self.retranslateUi(SelectorFiltros)
        self.check_organismo.toggled['bool'].connect(self.combox_organismo.update) # type: ignore
        self.check_error.toggled['bool'].connect(self.dsbox_error.update) # type: ignore
        self.check_p.toggled['bool'].connect(self.dsbox_p.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectorFiltros)

    def retranslateUi(self, SelectorFiltros):
        _translate = QtCore.QCoreApplication.translate
        SelectorFiltros.setWindowTitle(_translate("SelectorFiltros", "Selector de filtros"))
        self.label_organismo.setText(_translate("SelectorFiltros", "Organismo"))
        self.combox_organismo.setItemText(0, _translate("SelectorFiltros", "Todos"))
        self.combox_organismo.setItemText(1, _translate("SelectorFiltros", "Homo Sapiens"))
        self.label_error.setText(_translate("SelectorFiltros", "Error estándar máximo (%)"))
        self.label_p.setText(_translate("SelectorFiltros", "p-value máximo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectorFiltros = QtWidgets.QDialog()
    ui = Ui_SelectorFiltros()
    ui.setupUi(SelectorFiltros)
    SelectorFiltros.show()
    sys.exit(app.exec_())
