# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(381, 285)
        self.centralwidget = QtWidgets.QWidget(Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.bot_abrir_parseador = QtWidgets.QPushButton(self.centralwidget)
        self.bot_abrir_parseador.setGeometry(QtCore.QRect(70, 140, 91, 21))
        self.bot_abrir_parseador.setObjectName("bot_abrir_parseador")
        self.bot_abrir_graficador = QtWidgets.QPushButton(self.centralwidget)
        self.bot_abrir_graficador.setGeometry(QtCore.QRect(220, 140, 91, 23))
        self.bot_abrir_graficador.setObjectName("bot_abrir_graficador")
        Menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Menu)
        self.bot_abrir_parseador.clicked.connect(Menu.update) # type: ignore
        self.bot_abrir_graficador.clicked.connect(Menu.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Menu"))
        self.bot_abrir_parseador.setText(_translate("Menu", "Abrir parseador"))
        self.bot_abrir_graficador.setText(_translate("Menu", "Abrir graficador"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QMainWindow()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
