# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\parseador.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Parseador(object):
    def setupUi(self, Parseador):
        Parseador.setObjectName("Parseador")
        Parseador.resize(319, 265)
        self.path_file = QtWidgets.QLineEdit(Parseador)
        self.path_file.setGeometry(QtCore.QRect(50, 70, 113, 20))
        self.path_file.setObjectName("path_file")
        self.select_file = QtWidgets.QPushButton(Parseador)
        self.select_file.setGeometry(QtCore.QRect(180, 70, 71, 21))
        self.select_file.setObjectName("select_file")
        self.formato_log = QtWidgets.QComboBox(Parseador)
        self.formato_log.setEnabled(False)
        self.formato_log.setGeometry(QtCore.QRect(50, 170, 69, 22))
        self.formato_log.setObjectName("formato_log")
        self.formato_log.addItem("")
        self.label_formato = QtWidgets.QLabel(Parseador)
        self.label_formato.setGeometry(QtCore.QRect(60, 150, 47, 13))
        self.label_formato.setObjectName("label_formato")
        self.bot_parsear = QtWidgets.QPushButton(Parseador)
        self.bot_parsear.setEnabled(False)
        self.bot_parsear.setGeometry(QtCore.QRect(160, 170, 75, 23))
        self.bot_parsear.setObjectName("bot_parsear")
        self.label_formato.setBuddy(self.formato_log)

        self.retranslateUi(Parseador)
        self.select_file.clicked.connect(self.path_file.update) # type: ignore
        self.path_file.editingFinished.connect(self.formato_log.update) # type: ignore
        self.path_file.editingFinished.connect(self.bot_parsear.showMenu) # type: ignore
        self.path_file.editingFinished.connect(self.label_formato.update) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Parseador)
        Parseador.setTabOrder(self.path_file, self.select_file)
        Parseador.setTabOrder(self.select_file, self.formato_log)
        Parseador.setTabOrder(self.formato_log, self.bot_parsear)

    def retranslateUi(self, Parseador):
        _translate = QtCore.QCoreApplication.translate
        Parseador.setWindowTitle(_translate("Parseador", "Parseador"))
        self.select_file.setText(_translate("Parseador", "Seleccionar"))
        self.formato_log.setItemText(0, _translate("Parseador", "Apache"))
        self.label_formato.setText(_translate("Parseador", "Formato"))
        self.bot_parsear.setText(_translate("Parseador", "Parsear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Parseador = QtWidgets.QDialog()
    ui = Ui_Parseador()
    ui.setupUi(Parseador)
    Parseador.show()
    sys.exit(app.exec_())
