# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selector_opcion.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectorOpcion(object):
    def setupUi(self, SelectorOpcion):
        SelectorOpcion.setObjectName("SelectorOpcion")
        SelectorOpcion.resize(285, 169)
        self.gridLayout = QtWidgets.QGridLayout(SelectorOpcion)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_opcion = QtWidgets.QLabel(SelectorOpcion)
        self.label_opcion.setAlignment(QtCore.Qt.AlignCenter)
        self.label_opcion.setObjectName("label_opcion")
        self.horizontalLayout.addWidget(self.label_opcion)
        self.combox_opciones = QtWidgets.QComboBox(SelectorOpcion)
        self.combox_opciones.setEnabled(True)
        self.combox_opciones.setObjectName("combox_opciones")
        self.combox_opciones.addItem("")
        self.combox_opciones.setItemText(0, "")
        self.horizontalLayout.addWidget(self.combox_opciones)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.bbox = QtWidgets.QDialogButtonBox(SelectorOpcion)
        self.bbox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.bbox.setObjectName("bbox")
        self.gridLayout.addWidget(self.bbox, 2, 2, 1, 1)

        self.retranslateUi(SelectorOpcion)
        QtCore.QMetaObject.connectSlotsByName(SelectorOpcion)

    def retranslateUi(self, SelectorOpcion):
        _translate = QtCore.QCoreApplication.translate
        SelectorOpcion.setWindowTitle(_translate("SelectorOpcion", "Selector"))
        self.label_opcion.setText(_translate("SelectorOpcion", "Opción"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SelectorOpcion = QtWidgets.QDialog()
    ui = Ui_SelectorOpcion()
    ui.setupUi(SelectorOpcion)
    SelectorOpcion.show()
    sys.exit(app.exec_())
